{{- $comp := "kafka" -}}
{{- $vals := .Values.kafka -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $comp }}
  labels:
    app.kubernetes.io/component: {{ $comp }}
    {{- include "mastodon-agent-mlops.labels" . | nindent 4 }}
spec:
  replicas: {{ $vals.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $comp }}
      {{- include "mastodon-agent-mlops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $comp }}
        {{- include "mastodon-agent-mlops.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kafka
          image: {{ $vals.image }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy $vals.pullPolicy }}
          ports:
            - containerPort: {{ $vals.service.ports.client }}
              name: client
            - containerPort: {{ $vals.service.ports.controller }}
              name: controller
          env:
            {{- range $key, $value := $vals.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $comp }}
  labels:
    app.kubernetes.io/component: {{ $comp }}
    {{- include "mastodon-agent-mlops.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: {{ $comp }}
    {{- include "mastodon-agent-mlops.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ $vals.service.ports.client }}
      targetPort: {{ $vals.service.ports.client }}
    - name: controller
      port: {{ $vals.service.ports.controller }}
      targetPort: {{ $vals.service.ports.controller }}
